# Quiz19

In [15]:
import numpy as np
a = np.random.randint(10,101,(5,5))
print(a)

b = a[a>50]
print(b)

[[16 46 76 88 87]
 [68 71 54 93 54]
 [44 49 47 49 31]
 [91 28 46 18 23]
 [73 80 42 43 51]]
[76 88 87 68 71 54 93 54 91 73 80 51]
