In [2]:
import numpy as np
x = np.arange(1,26)
y = x.reshape(5,5)
print(y)
print(" ")

print(y[3,0],y[3,1],y[4,0],y[4,1])
print('or')
print(y[3:5,0:2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
 
16 17 21 22
or
[[16 17]
 [21 22]]
