# Quiz 18

In [50]:
import numpy as np
a = np.random.randint(10,101,(5,5))
print(a)

b = a.reshape((25))
print(b)

c = []
for i in b:
    if i>50:
        c.append(i)
    else:
        c.append(0)
d = np.array(c)
print('Answer is')
print(d.reshape(5,5))




[[12 16 52 90 33]
 [96 28 57 39 64]
 [45 23 67 64 62]
 [12 28 30 94 29]
 [47 12 43 56 13]]
[12 16 52 90 33 96 28 57 39 64 45 23 67 64 62 12 28 30 94 29 47 12 43 56
 13]
Answer is
[[ 0  0 52 90  0]
 [96  0 57  0 64]
 [ 0  0 67 64 62]
 [ 0  0  0 94  0]
 [ 0  0  0 56  0]]
