In [30]:
import numpy as np
numberList = []
for i in range(9): 
    print("Enter number at location", i, ":")
    item = int(input())
    while item < 10 or item >100 or item in numberList: 
        item = int(input())
    numberList.append(item)
print("User List is ", numberList)
arr = np.array(numberList)
arr2 =arr.reshape(3,3)
print("Array reshape 3*3 is \n",arr2)
Transapose = arr2.T
print("Result is \n",c)

Enter number at location 0 :
11
Enter number at location 1 :
12
Enter number at location 2 :
13
Enter number at location 3 :
14
Enter number at location 4 :
15
Enter number at location 5 :
16
Enter number at location 6 :
17
Enter number at location 7 :
18
Enter number at location 8 :
19
User List is  [11, 12, 13, 14, 15, 16, 17, 18, 19]
Array reshape 3*3 is [[11 12 13]
 [14 15 16]
 [17 18 19]]
Result is 
 [[11 14 17]
 [12 15 18]
 [13 16 19]]


## 