# Quiz 13

In [29]:
import numpy as np
x = np.arange(1,26)
y = x.reshape(5,5)
print(y)
print(" ")
print('Result Quiz 13')
print(y[1:3,2:4])    

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
 
Result Quiz 13
[[ 8  9]
 [13 14]]
