# Quiz 12

In [10]:
import numpy as np
x = np.random.randint(50,100,(4,4))
print(x)
y = x
y.T

[[90 53 78 79]
 [97 88 80 74]
 [94 75 95 55]
 [74 60 68 52]]


array([[90, 97, 94, 74],
       [53, 88, 75, 60],
       [78, 80, 95, 68],
       [79, 74, 55, 52]])